/* Freiweit mit Nihat — Shared Language System */
(function(){
var TI={
  de:{
    /* Nav */
    nav_mediakit:'Media Kit anfordern',nav_beratung:'Beratung buchen',
    /* Megamenu Themen */
    mega_themen_label:'Was kann ich für dich tun?',
    mtt_beratung:'Auswandern & Beratung',mtt_beratung_sub:'Visa, Kosten, erster Schritt',
    mtt_nomade:'Digitaler Nomade',mtt_nomade_sub:'Remote work, Co-working',
    mtt_mieten:'Mieten',mtt_mieten_sub:'Wohnung oder Haus',
    mtt_kaufen:'Kaufen',mtt_kaufen_sub:'Immobilien in Asien',
    mtt_hotel:'Hotel & Reise',mtt_hotel_sub:'Empfehlungen & Tipps',
    mtt_business:'Business & Kooperation',mtt_business_sub:'Sponsored, Affiliate',
    mtt_cityguides:'City Guides',mtt_cityguides_sub:'Pattaya, Bangkok & mehr',
    mtt_ratgeber:'Kostenloser Ratgeber',mtt_ratgeber_sub:'7 Fehler beim Auswandern',
    /* Megamenu Spalten */
    mega_thailand:'Thailand',mega_vietnam:'Vietnam',mega_yt:'YouTube & Links',
    mg_grab:'Grab App einrichten',mg_grab_sub:'Taxi, Essen, Pakete in ganz SEA',
    mg_visa_th:'Thailand E-Visum',mg_visa_th_sub:'Anleitung + alle Visa-Optionen',
    mg_tdac:'Thailand Digital Arrival Card',mg_tdac_sub:'Pflicht seit 2024 — so geht es',
    mg_kosten_th:'Lebenshaltungskosten Thailand',mg_kosten_th_sub:'Pattaya, Chiang Mai, Bangkok',
    mg_immo_th:'Immobilien Thailand',mg_immo_th_sub:'Mieten & Kaufen aus meinen Videos',
    mg_visa_vn:'Vietnam E-Visum',mg_visa_vn_sub:'Anleitung + offizieller Antrag',
    mg_grab_vn:'Grab App Vietnam',mg_grab_vn_sub:'Da Nang, Hanoi, Ho-Chi-Minh',
    mg_sim_vn:'SIM-Karte Vietnam',mg_sim_vn_sub:'Welche SIM, wo kaufen, was kostet es',
    mg_kosten_vn:'Lebenshaltungskosten Vietnam',mg_kosten_vn_sub:'Da Nang, Hanoi, HCMC — aus erster Hand',
    mg_guides:'City Guides kaufen',mg_guides_sub:'Google Maps Geheimtipps ab 9,90€',
    mg_immo_vn:'Immobilien Vietnam',mg_immo_vn_sub:'Wohnungen & Häuser mit echten Preisen',
    mg_yt:'YouTube Kanal',mg_yt_sub:'Wöchentlich neue Videos — kostenlos',
    mg_beratung:'1-on-1 Beratung — 97€',mg_beratung_sub:'60 Min. zu Visa, Budget, Wohnen',
    mg_interview:'Interview anfragen',mg_interview_sub:'Als Expat im Video auftreten',
    mg_mediakit:'Media Kit anfordern',mg_mediakit_sub:'Sponsoring & Kooperationen',
    mg_community:'Telegram Community',mg_community_sub:'Austausch mit Gleichgesinnten',
    /* Index Hero */
    hero_eyebrow:'7 Jahre · 70+ Länder',
    hero_h1:'Leben im Ausland.<br>Ehrlich. Direkt.<br>Aus erster Hand.',
    hero_sub:'Ich bin Nihat — Backpacker seit 2018, aktuell in Thailand und Vietnam. Kein Influencer-Lifestyle, kein Bullshit. Nur das, was wirklich zählt.',
    hero_cta_book:'Beratung buchen — 97€',
    hero_cta_yt:'Zum YouTube-Kanal',
    /* Index Stats */
    stat_years:'Jahre unterwegs',stat_countries:'Länder bereist',stat_videos:'Videos produziert',
    /* Index Offer Section */
    offer_title:'Was du hier findest',
    offer_sub:'Vom ersten Gedanken bis zum eigenen Apartment in Asien',
    /* Angebot Kacheln */
    tile_yt_label:'YouTube',tile_yt_title:'Wöchentliche Videos',tile_yt_sub:'Ehrliche Einblicke in Leben, Kosten und Alltag im Ausland.',
    tile_guides_label:'City Guides',tile_guides_title:'Google Maps Geheimtipps',tile_guides_sub:'Restaurants, Märkte, Unterkünfte — handverlesen aus meinen Reisen.',
    tile_beratung_label:'Beratung',tile_beratung_title:'1-on-1 mit Nihat',tile_beratung_sub:'60 Minuten für deine konkrete Situation. Visa, Kosten, Wohnen.',
    tile_ratgeber_label:'Ratgeber',tile_ratgeber_title:'7 größte Fehler',tile_ratgeber_sub:'Kostenlos. Was ich selbst falsch gemacht habe — damit du es nicht musst.',
    tile_immo_label:'Immobilien',tile_immo_title:'Wohnungen & Häuser',tile_immo_sub:'Echte Objekte, echte Preise. Thailand & Vietnam.',
    tile_community_label:'Community',tile_community_title:'Telegram Gruppe',tile_community_sub:'Tausch dich mit Gleichgesinnten aus.',
    /* Blog Section */
    blog_title:'Aus dem Blog',
    blog_sub:'Erfahrungen, Analysen, Zahlen — keine Werbebotschaften',
    blog_readmore:'Artikel lesen',
    /* CTA Section */
    cta_title:'Bereit für den nächsten Schritt?',
    cta_sub:'Buch dir 60 Minuten mit mir. Wir gehen deine Situation durch — Visa, Budget, Wohnungssuche, alles.',
    cta_btn:'Beratungsgespräch buchen — 97€',
    cta_or:'oder',
    cta_yt:'Erst mal die Videos ansehen',
    /* Footer */

    /* Hero */
    hero_eyebrow:'7 Jahre &middot; 70+ L\u00e4nder',
    hero_h1:'Leben.<br>Reisen.<br><em>Freiweit.</em>',
    hero_sub:'Ich zeige dir wie das Leben im Ausland wirklich aussieht \u2014 mit echten Zahlen, echten Fehlern und ohne Sch\u00f6nf\u00e4rberei. Damit du deinen Schritt machst.',
    hero_btn_yt:'YouTube ansehen',
    hero_btn_beratung:'Beratung buchen',
    hero_btn_immo:'Mieten &amp; Kaufen',
    hero_btn_auswandern:'Auswandern',
    hero_btn_verkaufen:'Verkaufen',
    hero_btn_interview:'Interview',
    stat_countries:'L\u00e4nder bereist',
    stat_years:'Jahre unterwegs',
    stat_unfiltered:'Ungefiltert',
    stat_languages:'Sprachen',
    /* Angebote */
    offer_eyebrow:'Was ich anbiete',
    offer_h2:'Alles was du brauchst,<br>um den Schritt zu machen.',
    oc_yt_title:'YouTube Videos',
    oc_yt_desc:'W\u00f6chentlich neue Videos \u2014 Kosten, Visa, Alltag, Interviews mit echten Expats.',
    oc_yt_cta:'Kostenlos ansehen \u2192',
    oc_guides_title:'City Guides',
    oc_beratung_title:'1-on-1 Beratung',
    oc_ratgeber_title:'Kostenloser Ratgeber',
    oc_immo_title:'Immobilien',
    oc_community_title:'Community',
    /* Blog */
    blog_eyebrow:'Blog &amp; Videos',
    blog_h2:'Aktuelle Einblicke.',
    blog_sub:'Jedes neue Video erscheint auch hier als Artikel.',
    /* Kontakt */
    contact_eyebrow:'Kontakt',
    contact_h2:'Schreib mir.',
    contact_title:'Ich antworte pers\u00f6nlich.',
    footer_links:'Impressum &middot; Datenschutz',
  },
  en:{
    nav_mediakit:'Request Media Kit',nav_beratung:'Book Consultation',
    mega_themen_label:'What can I help you with?',
    mtt_beratung:'Moving Abroad & Consulting',mtt_beratung_sub:'Visa, costs, first steps',
    mtt_nomade:'Digital Nomad',mtt_nomade_sub:'Remote work, co-working',
    mtt_mieten:'Rent',mtt_mieten_sub:'Apartment or house',
    mtt_kaufen:'Buy',mtt_kaufen_sub:'Real estate in Asia',
    mtt_hotel:'Hotel & Travel',mtt_hotel_sub:'Recommendations & tips',
    mtt_business:'Business & Partnerships',mtt_business_sub:'Sponsored, affiliate',
    mtt_cityguides:'City Guides',mtt_cityguides_sub:'Pattaya, Bangkok & more',
    mtt_ratgeber:'Free Guide',mtt_ratgeber_sub:'7 mistakes when emigrating',
    mega_thailand:'Thailand',mega_vietnam:'Vietnam',mega_yt:'YouTube & Links',
    mg_grab:'Set up Grab App',mg_grab_sub:'Taxi, food, packages across SEA',
    mg_visa_th:'Thailand E-Visa',mg_visa_th_sub:'Guide + all visa options',
    mg_tdac:'Thailand Digital Arrival Card',mg_tdac_sub:'Mandatory since 2024 — how it works',
    mg_kosten_th:'Cost of Living Thailand',mg_kosten_th_sub:'Pattaya, Chiang Mai, Bangkok',
    mg_immo_th:'Real Estate Thailand',mg_immo_th_sub:'Rent & buy from my videos',
    mg_visa_vn:'Vietnam E-Visa',mg_visa_vn_sub:'Guide + official application',
    mg_grab_vn:'Grab App Vietnam',mg_grab_vn_sub:'Da Nang, Hanoi, Ho Chi Minh City',
    mg_sim_vn:'SIM Card Vietnam',mg_sim_vn_sub:'Which SIM, where to buy, what it costs',
    mg_kosten_vn:'Cost of Living Vietnam',mg_kosten_vn_sub:'Da Nang, Hanoi, HCMC — first hand',
    mg_guides:'Buy City Guides',mg_guides_sub:'Google Maps insider tips from €9.90',
    mg_immo_vn:'Real Estate Vietnam',mg_immo_vn_sub:'Apartments & houses with real prices',
    mg_yt:'YouTube Channel',mg_yt_sub:'New videos weekly — free',
    mg_beratung:'1-on-1 Consultation — €97',mg_beratung_sub:'60 min on visa, budget, housing',
    mg_interview:'Apply for Interview',mg_interview_sub:'Appear as expat in a video',
    mg_mediakit:'Request Media Kit',mg_mediakit_sub:'Sponsoring & cooperations',
    mg_community:'Telegram Community',mg_community_sub:'Connect with like-minded people',
    hero_eyebrow:'7 Years · 70+ Countries',
    hero_h1:'Life Abroad.<br>Honest. Direct.<br>First Hand.',
    hero_sub:"I'm Nihat — backpacking since 2018, currently based in Thailand and Vietnam. No influencer lifestyle, no BS. Just what actually matters.",
    hero_cta_book:'Book Consultation — €97',
    hero_cta_yt:'Go to YouTube Channel',
    stat_years:'years traveling',stat_countries:'countries visited',stat_videos:'videos produced',
    offer_title:'What you find here',
    offer_sub:'From the first thought to your own apartment in Asia',
    tile_yt_label:'YouTube',tile_yt_title:'Weekly Videos',tile_yt_sub:'Honest insights into life, costs and everyday life abroad.',
    tile_guides_label:'City Guides',tile_guides_title:'Google Maps Insider Tips',tile_guides_sub:'Restaurants, markets, accommodation — handpicked from my travels.',
    tile_beratung_label:'Consulting',tile_beratung_title:'1-on-1 with Nihat',tile_beratung_sub:'60 minutes for your specific situation. Visa, costs, housing.',
    tile_ratgeber_label:'Guide',tile_ratgeber_title:'7 Biggest Mistakes',tile_ratgeber_sub:'Free. What I did wrong myself — so you don\'t have to.',
    tile_immo_label:'Real Estate',tile_immo_title:'Apartments & Houses',tile_immo_sub:'Real properties, real prices. Thailand & Vietnam.',
    tile_community_label:'Community',tile_community_title:'Telegram Group',tile_community_sub:'Connect with like-minded people.',
    blog_title:'From the Blog',
    blog_sub:'Experiences, analysis, numbers — no advertising messages',
    blog_readmore:'Read article',
    cta_title:'Ready for the next step?',
    cta_sub:'Book 60 minutes with me. We go through your situation — visa, budget, apartment search, everything.',
    cta_btn:'Book Consultation — €97',
    cta_or:'or',
    cta_yt:'Watch the videos first',

    /* Hero */
    hero_eyebrow:'7 Years &middot; 70+ Countries',
    hero_h1:'Live.<br>Travel.<br><em>Freely.</em>',
    hero_sub:'I show you what life abroad really looks like \u2014 with real numbers, real mistakes and no sugarcoating. So you can make your move.',
    hero_btn_yt:'Watch YouTube',
    hero_btn_beratung:'Book Consultation',
    hero_btn_immo:'Rent &amp; Buy',
    hero_btn_auswandern:'Emigrate',
    hero_btn_verkaufen:'Sell',
    hero_btn_interview:'Interview',
    stat_countries:'Countries visited',
    stat_years:'Years traveling',
    stat_unfiltered:'Unfiltered',
    stat_languages:'Languages',
    /* Angebote */
    offer_eyebrow:'What I offer',
    offer_h2:'Everything you need,<br>to make your move.',
    oc_yt_title:'YouTube Videos',
    oc_yt_desc:'New videos weekly \u2014 costs, visas, daily life, interviews with real expats.',
    oc_yt_cta:'Watch for free \u2192',
    oc_guides_title:'City Guides',
    oc_beratung_title:'1-on-1 Consulting',
    oc_ratgeber_title:'Free Guide',
    oc_immo_title:'Real Estate',
    oc_community_title:'Community',
    /* Blog */
    blog_eyebrow:'Blog &amp; Videos',
    blog_h2:'Latest Insights.',
    blog_sub:'Every new video also appears here as an article.',
    /* Contact */
    contact_eyebrow:'Contact',
    contact_h2:'Write to me.',
    contact_title:'I respond personally.',
    footer_links:'Imprint &middot; Privacy',
  },
  th:{
    nav_mediakit:'ขอ Media Kit',nav_beratung:'จองปรึกษา',
    mega_themen_label:'ฉันช่วยคุณได้อะไร?',
    mtt_beratung:'ย้ายต่างประเทศ & ปรึกษา',mtt_beratung_sub:'วีซ่า ค่าใช้จ่าย เริ่มต้น',
    mtt_nomade:'นอมาดดิจิทัล',mtt_nomade_sub:'ทำงานบนนั้น Co-working',
    mtt_mieten:'เช่า',mtt_mieten_sub:'อพาร์ตเมนต์หรือบ้าน',
    mtt_kaufen:'ซื้อ',mtt_kaufen_sub:'อสังหาริมทรัพย์ในเอเชีย',
    mtt_hotel:'โรแรม & การเดินทาง',mtt_hotel_sub:'คำแนะนำ & เคล็ดลับ',
    mtt_business:'ธุรกิจ & ความร่วมมือ',mtt_business_sub:'สปอนเซอร์ Affiliate',
    mtt_cityguides:'City Guides',mtt_cityguides_sub:'พัทยา กรุงเทพ & อื่นๆ',
    mtt_ratgeber:'คู่มือฟรี',mtt_ratgeber_sub:'7 ข้อผิดพลาดในการย้ายถิ่น',
    mega_thailand:'ประเทศไทย',mega_vietnam:'เวียดนาม',mega_yt:'YouTube & ลิงก์',
    mg_grab:'ตั้งค่าแอป Grab',mg_grab_sub:'แท็กซี่ อาหาร พัสดุทั่ว SEA',
    mg_visa_th:'วีซ่า E-Visa ไทย',mg_visa_th_sub:'คู่มือ + ตัวเลือกวีซ่าทั้งหมด',
    mg_tdac:'บัตรเข้าเมืองดิจิทัลไทย',mg_tdac_sub:'บังคับตั้งแต่ 2024 — วิธีทำ',
    mg_kosten_th:'ค่าครองชีพในไทย',mg_kosten_th_sub:'พัทยา เชียงใหม่ กรุงเทพ',
    mg_immo_th:'อสังหาริมทรัพย์ไทย',mg_immo_th_sub:'เช่าและซื้อจากวิดีโอ',
    mg_visa_vn:'E-Visa เวียดนาม',mg_visa_vn_sub:'คู่มือ + สมัครอย่างเป็นทางการ',
    mg_grab_vn:'Grab แอป เวียดนาม',mg_grab_vn_sub:'ดานัง ฮานอย โฮจิมินห์',
    mg_sim_vn:'ซิมการ์ดเวียดนาม',mg_sim_vn_sub:'ซิมไหน ซื้อที่ไหน ราคาเท่าไหร่',
    mg_kosten_vn:'ค่าครองชีพเวียดนาม',mg_kosten_vn_sub:'ดานัง ฮานอย HCMC',
    mg_guides:'ซื้อ City Guides',mg_guides_sub:'เคล็ดลับ Google Maps ตั้งแต่ 9.90€',
    mg_immo_vn:'อสังหาริมทรัพย์เวียดนาม',mg_immo_vn_sub:'อพาร์ตเมนต์และบ้านราคาจริง',
    mg_yt:'ช่อง YouTube',mg_yt_sub:'วิดีโอใหม่ทุกสัปดาห์ — ฟรี',
    mg_beratung:'ปรึกษาส่วนตัว — 97€',mg_beratung_sub:'60 นาที วีซ่า งบ ที่พัก',
    mg_interview:'สมัครสัมภาษณ์',mg_interview_sub:'ปรากฏในวิดีโอในฐานะ Expat',
    mg_mediakit:'ขอ Media Kit',mg_mediakit_sub:'สปอนเซอร์ & ความร่วมมือ',
    mg_community:'Telegram Community',mg_community_sub:'พูดคุยกับคนที่มีความคิดเหมือนกัน',
    hero_eyebrow:'7 ปี · 70+ ประเทศ',
    hero_h1:'ชีวิตต่างแดน<br>ตรงไปตรงมา<br>จากประสบการณ์จริง',
    hero_sub:'ฉันชื่อ Nihat — เดินทางตั้งแต่ 2018 ตอนนี้อยู่ไทยและเวียดนาม ไม่มีไลฟ์สไตล์อินฟลูเอนเซอร์ แค่ความจริงที่สำคัญ',
    hero_cta_book:'จองปรึกษา — 97€',
    hero_cta_yt:'ไปยังช่อง YouTube',
    stat_years:'ปีที่เดินทาง',stat_countries:'ประเทศที่ไปแล้ว',stat_videos:'วิดีโอที่ผลิต',
    offer_title:'สิ่งที่คุณพบที่นี่',
    offer_sub:'จากความคิดแรกจนมีอพาร์ตเมนต์ของตัวเองในเอเชีย',
    tile_yt_label:'YouTube',tile_yt_title:'วิดีโอรายสัปดาห์',tile_yt_sub:'ข้อมูลจริงเกี่ยวกับชีวิต ค่าใช้จ่าย และชีวิตประจำวันในต่างประเทศ',
    tile_guides_label:'City Guides',tile_guides_title:'เคล็ดลับ Google Maps',tile_guides_sub:'ร้านอาหาร ตลาด ที่พัก — คัดสรรจากการเดินทาง',
    tile_beratung_label:'ปรึกษา',tile_beratung_title:'ส่วนตัวกับ Nihat',tile_beratung_sub:'60 นาทีสำหรับสถานการณ์ของคุณ วีซ่า ค่าใช้จ่าย ที่พัก',
    tile_ratgeber_label:'คู่มือ',tile_ratgeber_title:'7 ข้อผิดพลาดใหญ่',tile_ratgeber_sub:'ฟรี สิ่งที่ฉันทำผิดเอง — เพื่อคุณจะได้ไม่ต้องทำ',
    tile_immo_label:'อสังหา',tile_immo_title:'อพาร์ตเมนต์ & บ้าน',tile_immo_sub:'อสังหาริมทรัพย์จริง ราคาจริง ไทยและเวียดนาม',
    tile_community_label:'คอมมูนิตี้',tile_community_title:'กลุ่ม Telegram',tile_community_sub:'แลกเปลี่ยนกับคนที่มีความคิดเหมือนกัน',
    blog_title:'จากบล็อก',
    blog_sub:'ประสบการณ์ การวิเคราะห์ ตัวเลข — ไม่มีโฆษณา',
    blog_readmore:'อ่านบทความ',
    cta_title:'พร้อมสำหรับขั้นตอนต่อไปหรือยัง?',
    cta_sub:'จอง 60 นาทีกับฉัน เราจะพูดถึงสถานการณ์ของคุณ วีซ่า งบ การหาที่อยู่อาศัย ทุกอย่าง',
    cta_btn:'จองปรึกษา — 97€',
    cta_or:'หรือ',
    cta_yt:'ดูวิดีโอก่อน',

    /* Hero */
    hero_eyebrow:'7 \u0e1b\u0e35 &middot; 70+ \u0e1b\u0e23\u0e30\u0e40\u0e17\u0e28',
    hero_h1:'\u0e43\u0e0a\u0e49\u0e0a\u0e35\u0e27\u0e34\u0e15<br>\u0e40\u0e14\u0e34\u0e19\u0e17\u0e32\u0e07<br><em>\u0e2d\u0e34\u0e2a\u0e23\u0e30</em>',
    hero_sub:'\u0e09\u0e31\u0e19\u0e41\u0e2a\u0e14\u0e07\u0e43\u0e2b\u0e49\u0e04\u0e38\u0e13\u0e40\u0e2b\u0e47\u0e19\u0e27\u0e48\u0e32\u0e0a\u0e35\u0e27\u0e34\u0e15\u0e43\u0e19\u0e15\u0e48\u0e32\u0e07\u0e1b\u0e23\u0e30\u0e40\u0e17\u0e28\u0e40\u0e1b\u0e47\u0e19\u0e2d\u0e22\u0e48\u0e32\u0e07\u0e44\u0e23\u0e08\u0e23\u0e34\u0e07\u0e46 \u2014 \u0e14\u0e49\u0e27\u0e22\u0e15\u0e31\u0e27\u0e40\u0e25\u0e02\u0e08\u0e23\u0e34\u0e07 \u0e04\u0e27\u0e32\u0e21\u0e1c\u0e34\u0e14\u0e1e\u0e25\u0e32\u0e14\u0e08\u0e23\u0e34\u0e07 \u0e41\u0e25\u0e30\u0e44\u0e21\u0e48\u0e21\u0e35\u0e01\u0e32\u0e23\u0e1b\u0e23\u0e38\u0e07\u0e41\u0e15\u0e48\u0e07',
    hero_btn_yt:'\u0e14\u0e39 YouTube',
    hero_btn_beratung:'\u0e08\u0e2d\u0e07\u0e1b\u0e23\u0e36\u0e01\u0e29\u0e32',
    hero_btn_immo:'\u0e40\u0e0a\u0e48\u0e32 &amp; \u0e0b\u0e37\u0e49\u0e2d',
    hero_btn_auswandern:'\u0e22\u0e49\u0e32\u0e22\u0e44\u0e1b\u0e15\u0e48\u0e32\u0e07\u0e1b\u0e23\u0e30\u0e40\u0e17\u0e28',
    hero_btn_verkaufen:'\u0e02\u0e32\u0e22',
    hero_btn_interview:'\u0e2a\u0e31\u0e21\u0e20\u0e32\u0e29\u0e13\u0e4c',
    stat_countries:'\u0e1b\u0e23\u0e30\u0e40\u0e17\u0e28\u0e17\u0e35\u0e48\u0e44\u0e1b\u0e41\u0e25\u0e49\u0e27',
    stat_years:'\u0e1b\u0e35\u0e17\u0e35\u0e48\u0e40\u0e14\u0e34\u0e19\u0e17\u0e32\u0e07',
    stat_unfiltered:'\u0e44\u0e21\u0e48\u0e01\u0e23\u0e2d\u0e07',
    stat_languages:'\u0e20\u0e32\u0e29\u0e32',
    /* Angebote */
    offer_eyebrow:'\u0e2a\u0e34\u0e48\u0e07\u0e17\u0e35\u0e48\u0e09\u0e31\u0e19\u0e40\u0e2a\u0e19\u0e2d',
    offer_h2:'\u0e17\u0e38\u0e01\u0e2d\u0e22\u0e48\u0e32\u0e07\u0e17\u0e35\u0e48\u0e04\u0e38\u0e13\u0e15\u0e49\u0e2d\u0e07\u0e01\u0e32\u0e23<br>\u0e40\u0e1e\u0e37\u0e48\u0e2d\u0e01\u0e49\u0e32\u0e27\u0e44\u0e1b\u0e02\u0e49\u0e32\u0e07\u0e2b\u0e19\u0e49\u0e32',
    oc_yt_title:'YouTube Videos',
    oc_yt_desc:'\u0e27\u0e34\u0e14\u0e35\u0e42\u0e2d\u0e43\u0e2b\u0e21\u0e48\u0e17\u0e38\u0e01\u0e2a\u0e31\u0e1b\u0e14\u0e32\u0e2b\u0e4c \u2014 \u0e04\u0e48\u0e32\u0e43\u0e0a\u0e49\u0e08\u0e48\u0e32\u0e22 \u0e27\u0e35\u0e0b\u0e48\u0e32 \u0e0a\u0e35\u0e27\u0e34\u0e15\u0e1b\u0e23\u0e30\u0e08\u0e33\u0e27\u0e31\u0e19',
    oc_yt_cta:'\u0e14\u0e39\u0e1f\u0e23\u0e35 \u2192',
    oc_guides_title:'City Guides',
    oc_beratung_title:'\u0e1b\u0e23\u0e36\u0e01\u0e29\u0e32\u0e2a\u0e48\u0e27\u0e19\u0e15\u0e31\u0e27',
    oc_ratgeber_title:'\u0e04\u0e39\u0e48\u0e21\u0e37\u0e2d\u0e1f\u0e23\u0e35',
    oc_immo_title:'\u0e2d\u0e2a\u0e31\u0e07\u0e2b\u0e32\u0e23\u0e34\u0e21\u0e17\u0e23\u0e31\u0e1e\u0e22\u0e4c',
    oc_community_title:'\u0e04\u0e2d\u0e21\u0e21\u0e39\u0e19\u0e34\u0e15\u0e35\u0e49',
    /* Blog */
    blog_eyebrow:'Blog &amp; Videos',
    blog_h2:'\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e25\u0e48\u0e32\u0e2a\u0e38\u0e14',
    blog_sub:'\u0e17\u0e38\u0e01\u0e27\u0e34\u0e14\u0e35\u0e42\u0e2d\u0e43\u0e2b\u0e21\u0e48\u0e08\u0e30\u0e1b\u0e23\u0e32\u0e01\u0e0f\u0e17\u0e35\u0e48\u0e19\u0e35\u0e48\u0e40\u0e1b\u0e47\u0e19\u0e1a\u0e17\u0e04\u0e27\u0e32\u0e21\u0e14\u0e49\u0e27\u0e22',
    /* Contact */
    contact_eyebrow:'\u0e15\u0e34\u0e14\u0e15\u0e48\u0e2d',
    contact_h2:'\u0e40\u0e02\u0e35\u0e22\u0e19\u0e2b\u0e32\u0e09\u0e31\u0e19',
    contact_title:'\u0e09\u0e31\u0e19\u0e15\u0e2d\u0e1a\u0e01\u0e25\u0e31\u0e1a\u0e14\u0e49\u0e27\u0e22\u0e15\u0e31\u0e27\u0e40\u0e2d\u0e07',
    footer_links:'\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25\u0e17\u0e32\u0e07\u0e01\u0e0e\u0e2b\u0e21\u0e32\u0e22 &middot; \u0e04\u0e27\u0e32\u0e21\u0e40\u0e1b\u0e47\u0e19\u0e2a\u0e48\u0e27\u0e19\u0e15\u0e31\u0e27',
  }
};

window.FREIWEIT_TI = TI;

window.setLang = function(l){
  localStorage.setItem('lang',l);
  document.querySelectorAll('.lang-btn').forEach(function(b){
    b.classList.toggle('active',b.dataset.lang===l);
  });
  document.querySelectorAll('[data-i18n]').forEach(function(el){
    var k=el.getAttribute('data-i18n');
    if(TI[l]&&TI[l][k]!==undefined)el.innerHTML=TI[l][k];
  });
  document.documentElement.lang=l==='th'?'th':l==='en'?'en':'de';
};

document.addEventListener('DOMContentLoaded',function(){
  var l=localStorage.getItem('lang')||'de';
  window.setLang(l);
});
})();
